kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv-volume-_HOSTNAME_
  labels:
    type: local
  namespace: _HOSTNAME_
spec:
  storageClassName: mongo
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/var/lib/aion/_HOSTNAME_/mnt/mongo_data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - _HOSTNAME_