apiVersion: apps/v1
kind: Deployment
metadata:
  name: aion-sendanything
spec:
  template:
    spec:
      containers:
        - name: aion-sendanything
          env:
            - name: CLIENT_PORT
              value: "31100"
      volumes:
        - name: data
          hostPath:
            path: /var/lib/aion/prj
