kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv-volume-default-NODE-NAME
  labels:
    type: local
spec:
  storageClassName: mongo-NODE-NAME
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/aion/default/mnt/mongo_data"
