apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: default
  labels:
    k8s-app: fluentd
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      serviceAccount: aion-default
      serviceAccountName: aion-default
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - env:
        - name: K8S_NODE_NAME
          value: "mercury"
        - name: POS_FILE
          value: /var/log/fluentd/fluentd-docker.pos
        - name: CA_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: BEARER_TOKEN_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
        name: fluentd
        image: latona/fluentd
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /config
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config-volume
        configMap:
          name: fluentd-conf
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-conf
  namespace: default
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  fluent.conf: |-
    <system>
      log_level info
    </system>

    <source>
    @type tail
    path /var/log/containers/*.log
    pos_file "#{ENV['POS_FILE']}"
    tag kubernetes.*
    time_format %Y-%m-%dT%H:%M:%S
    format json
    read_from_head true
    </source>

    <filter "kubernetes.var.log.containers.**.log">
      @type kubernetes_metadata
      ca_file "#{ENV['CA_FILE']}"
      bearer_token_file "#{ENV['BEARER_TOKEN_FILE']}"
      skip_labels true
      skip_container_metadata true
      skip_master_url true
      skip_namespace_metadata true
    </filter>

    <filter kubernetes.var.log.containers.register-face-to-guest-table-kube-001*.log>
      @type grep
      <regexp>
        key log
        pattern /updateGuest succeeded/
      </regexp>
    </filter>

    <match kubernetes.**>
      @type rewrite_tag_filter
      <rule>
        key $.kubernetes.container_name
        pattern  /aion-kanban-replicator/
        tag mongo.aion_kanban_replicator
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /aion-sendanything/
        tag mongo.aion_sendanything
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /aion-servicebroker/
        tag mongo.aion_servicebroker
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /aion-statuskanban/
        tag mongo.aion_statuskanban
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /authenticator/
        tag mongo.authenticator
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /data-sweeper-batch/
        tag mongo.data_sweeper_batch
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /data-sweeper/
        tag mongo.data_sweeper
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /event-driven-face-existence-detection/
        tag mongo.event-driven-face-existence-detection
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /azure-face-api-identifier-kube/
        tag mongo.azure-face-api-identifier-kube
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /fluentd/
        tag mongo.fluentd
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /load-balancer-for-omotebako-smartphone/
        tag mongo.load_balancer_for_omotebako_smartphone
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /mongo/
        tag mongo.mongo
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /mysql/
        tag mongo.mysql
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /redis-cluster/
        tag mongo.redis_cluster
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /azure-face-api-registrator-kube/
        tag mongo.azure-face-api-registrator-kube
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /register-face-to-guest-table-kube/
        tag mongo.register-face-to-guest-table-kube
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /ui-backend-for-omotebako-backup/
        tag mongo.ui_backend_for_omotebako_backup
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /ui-backend-for-omotebako-calendar/
        tag mongo.ui_backend_for_omotebako_calendar
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /ui-backend-for-omotebako-gif/
        tag mongo.ui_backend_for_omotebako_gif
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /ui-backend-for-omotebako-random-voice/
        tag mongo.ui_backend_for_omotebako_random_voice
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /ui-backend-for-omotebako-redis/
        tag mongo.ui_backend_for_omotebako_redis
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /ui-backend-for-omotebako-site-controller/
        tag mongo.ui_backend_for_omotebako_site_controller
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /ui-backend-for-omotebako-streaming-audio/
        tag mongo.ui_backend_for_omotebako_streaming_audio
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /ui-frontend-for-omotebako-mobile/
        tag mongo.ui_frontend_for_omotebako_mobile
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /ui-frontend-for-omotebako/
        tag mongo.ui_frontend_for_omotebako
      </rule>
      <rule>
        key $.kubernetes.container_name
        pattern  /ui-backend-for-omotebako/
        tag mongo.ui_backend_for_omotebako
      </rule>
    </match>

    <match mongo.**>
      @type mongo
      host mongo
      port 27017
      database k8s
      collection '${tag}'
      remove_tag_prefix mongo.
      <buffer>
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
    </match>