apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: default
  labels:
    k8s-app: fluentd
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      serviceAccount: aion-default
      serviceAccountName: aion-default
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - env:
        - name: K8S_NODE_NAME
          value: "your_node_name"
        - name: POS_FILE
          value: /var/log/fluentd/fluentd-docker.pos
        - name: CA_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: BEARER_TOKEN_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
        name: fluentd-for-containers-mongodb-kube
        image: latona/fluentd-for-containers-mongodb-kube
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /config
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config-volume
        configMap:
          name: fluentd-conf
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-conf
  namespace: default
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  fluent.conf: |-
    <system>
      log_level info
    </system>

    <source>
    @type tail
    path /var/log/containers/*.log
    pos_file "#{ENV['POS_FILE']}"
    tag kubernetes.*
    time_format %Y-%m-%dT%H:%M:%S
    format json
    read_from_head true
    </source>

    <filter "kubernetes.var.log.containers.**.log">
      @type kubernetes_metadata
      ca_file "#{ENV['CA_FILE']}"
      bearer_token_file "#{ENV['BEARER_TOKEN_FILE']}"
      skip_labels true
      skip_container_metadata true
      skip_master_url true
      skip_namespace_metadata true
    </filter>

    <match kubernetes.**>
      @type rewrite_tag_filter
      <rule>
        key $.kubernetes.container_name
        pattern  /hogehoge/
        tag mongo.hogehoge
      </rule>
    </match>

    <match mongo.**>
      @type mongo
      host mongo
      port 27017
      database k8s
      collection '${tag}'
      remove_tag_prefix mongo.
      <buffer>
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
    </match>