apiVersion: v1
kind: Service
metadata:
  labels:
    run: rabbitmq
  name: rabbitmq
  namespace: default
spec:
  ports:
  - name: rabbitmq-node
    nodePort: 32094
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: rabbitmq-mgmt
    nodePort: 32095
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    run: rabbitmq
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: rabbitmq
  name: rabbitmq
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rabbitmq
  strategy:
    rollingUpdate: null
  template:
    metadata:
      labels:
        run: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.9.5-management-alpine
        imagePullPolicy: IfNotPresent
        name: rabbitmq
        ports:
        - containerPort: 5672
        tty: true
        volumeMounts:
        - mountPath: /var/lib/rabbitmq/mnesia
          name: rabbitmq-data
      hostname: rabbitmq
      volumes:
      - hostPath:
          path: /var/lib/aion/default/Data/rabbitmq
        name: rabbitmq-data
