apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rabbitmq
  strategy:
    rollingUpdate:
  template:
    metadata:
      labels:
        run: rabbitmq
    spec:
      hostname: rabbitmq
      containers:
      - name: rabbitmq
        tty: true
        image: rabbitmq:3.9.5-management-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq/mnesia
      volumes:
      - name: rabbitmq-data
        hostPath:
          path: /var/lib/aion/default/Data/rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: rabbitmq
  name: rabbitmq
spec:
  selector:
    run: rabbitmq
  type: NodePort
  ports:
  - name: rabbitmq-node
    port: 5672
    protocol: TCP
    targetPort: 5672
    nodePort: 32094
  - name: rabbitmq-mgmt
    port: 15672
    protocol: TCP
    targetPort: 15672
    nodePort: 32095
