apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redis-cluster
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname=: _HOSTNAME_
