apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      run: prometheus
  strategy:
    rollingUpdate:
  template:
    metadata:
      labels:
        run: prometheus
    spec:
      serviceAccountName: prometheus-serviceaccount
      hostname: prometheus
      containers:
        - name: prometheus
          image: prom/prometheus:v2.17.2
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
          ports:
            - containerPort: 9090
              name: prometheus-ui
        - name: grafana
          image: grafana/grafana:6.7.3
          ports:
            - containerPort: 3000
              name: grafana-ui
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-data
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-pv-claim
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: prometheus
  name: prometheus
spec:
  selector:
    run: prometheus
  type: NodePort
  ports:
    - name: prometheus-ui
      port: 9090
      targetPort: 9090
      nodePort: 30081
    - name: grafana-ui
      port: 3000
      targetPort: 3000
      nodePort: 30082
---

