apiVersion: v1
kind: Service
metadata:
  name: aion-servicebroker
spec:
  topologyKeys:
    - "kubernetes.io/hostname"
  type: NodePort
  ports:
    - name: envoy-grpc
      port: 11110
      protocol: TCP
      targetPort: 11110
      nodePort: 31110
    - name: envoy-admin
      port: 10001
      protocol: TCP
      targetPort: 10001
