apiVersion: apps/v1
kind: Deployment
metadata:
  name: aion-servicebroker
spec:
  template:
    spec:
      serviceAccountName: aion-default
      containers:
        - name: aion-servicebroker
          env:
            - name: NAMESPACE
              value: default
            - name: REPOSITORY_PREFIX
              value: latonaio
      volumes:
        - name: config
          hostPath:
            path: /var/lib/aion/default/config
