apiVersion: v1
kind: Service
metadata:
  labels:
    run: aion-servicebroker
  name: aion-servicebroker
spec:
  selector:
    run: aion-servicebroker
  type: NodePort
  ports:
    - name: envoy-grpc
      port: 10000
      protocol: TCP
      targetPort: 10000
      nodePort: 31000
